const CONFIG={url:'https://miznxoykfoanaczitmit.supabase.co',key:'YOUR_SUPABASE_PUBLISHABLE_KEY'};
const hasSupabase=window.supabase&&CONFIG.key&&!CONFIG.key.includes('YOUR_');
const sb=hasSupabase?window.supabase.createClient(CONFIG.url,CONFIG.key):null;
const state={demo:false,user:null,page:'dashboard',products:[],customers:[],quotes:[],movements:[]};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:2}).format(Number(n)||0);
const date=n=>new Intl.DateTimeFormat('tr-TR',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(n));
function toast(text,type='ok'){const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=text;$('#toast-root').append(el);setTimeout(()=>el.remove(),2800)}
const demo={products:[{id:'p1',code:'KAB-001',name:'3x2,5 NYM Kablo',category:'Kablo',stock:148,unit:'m',purchase:42.5,sale:58},{id:'p2',code:'SİG-010',name:'Otomat Sigorta C16',category:'Pano',stock:7,unit:'adet',purchase:95,sale:135},{id:'p3',code:'KON-025',name:'Kontaktör 25A',category:'Pano',stock:23,unit:'adet',purchase:420,sale:575},{id:'p4',code:'KLM-050',name:'Klemens 4mm',category:'Pano',stock:4,unit:'adet',purchase:18,sale:29}],customers:[{id:'c1',name:'Örnek Otomasyon Ltd. Şti.',contact:'Ahmet Yılmaz',phone:'0532 000 00 00',tax_no:'1234567890',balance:18450,type:'Müşteri'},{id:'c2',name:'HIS Elektrik',contact:'Mehmet Kaya',phone:'0541 000 00 00',tax_no:'9876543210',balance:-6250,type:'Tedarikçi'}],quotes:[{id:'q1',quote_no:'TKL-2026-001',customer_id:'c1',date:'2026-08-15',items_count:6,total:38750,status:'Bekliyor'},{id:'q2',quote_no:'TKL-2026-002',customer_id:'c2',date:'2026-08-14',items_count:3,total:12600,status:'Onaylandı'}],movements:[{id:'m1',product_id:'p1',type:'Giriş',qty:100,note:'Depo girişi',created_at:'2026-08-15'},{id:'m2',product_id:'p2',type:'Çıkış',qty:8,note:'Pano üretimi',created_at:'2026-08-14'}]};
function loadDemo(){state.demo=true;Object.keys(demo).forEach(k=>state[k]=structuredClone(demo[k]));state.user={email:'demo@stokteklif.local'};enterApp()}
function enterApp(){ $('#auth-view').classList.add('hidden');$('#app-view').classList.remove('hidden'); $('#user-email').textContent=state.user?.email||'Demo kullanıcı'; setConnection(state.demo?'Demo modu':'Supabase');renderAll() }
function setConnection(label){$('#connection-label').textContent=label;$('#settings-connection').textContent=label;const d=$('#connection-dot');d.className='dot '+(label==='Supabase'?'ok':'');}
async function login(e){e.preventDefault();if(!sb){toast('Supabase anahtarı henüz eklenmemiş. Demo modu kullanılabilir.','bad');return}const {data,error}=await sb.auth.signInWithPassword({email:$('#login-email').value,password:$('#login-password').value});if(error){toast(error.message,'bad');return}state.user=data.user;await loadData();enterApp()}
async function logout(){if(sb&&!state.demo)await sb.auth.signOut();state.user=null;state.demo=false;$('#app-view').classList.add('hidden');$('#auth-view').classList.remove('hidden')}
async function loadData(){if(!sb)return;const [p,c,q,m]=await Promise.all([sb.from('products').select('*').order('name'),sb.from('customers').select('*').order('name'),sb.from('quotes').select('*').order('created_at',{ascending:false}),sb.from('stock_movements').select('*').order('created_at',{ascending:false})]);for(const r of [p,c,q,m])if(r.error)throw r.error;state.products=p.data||[];state.customers=c.data||[];state.quotes=q.data||[];state.movements=m.data||[]}
function navigate(page){state.page=page;$$('.page').forEach(x=>x.classList.remove('active-page'));$(`#page-${page}`).classList.add('active-page');$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$$('.bottom-nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===page));const titles={dashboard:['GENEL BAKIŞ','Dashboard'],products:['ENVANTER','Stoklar'],customers:['CARİ YÖNETİMİ','Cariler'],quotes:['SATIŞ','Teklifler'],movements:['HAREKET','Stok Hareketleri'],settings:['SİSTEM','Ayarlar']};$('#page-kicker').textContent=titles[page][0];$('#page-title').textContent=titles[page][1];$('#sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
function renderAll(){renderStats();renderProducts();renderCustomers();renderQuotes();renderMovements();renderDashboard()}
function renderStats(){const low=state.products.filter(p=>Number(p.stock)<=5).length;const balance=state.customers.reduce((a,c)=>a+Number(c.balance||0),0);$('#stat-products').textContent=state.products.length;$('#stat-low').textContent=low;$('#stat-quotes').textContent=state.quotes.length;$('#stat-balance').textContent=money(balance)}
function renderDashboard(){const qs=state.quotes.slice(0,5);$('#recent-quotes').innerHTML=qs.length?qs.map(q=>{const c=state.customers.find(x=>x.id===q.customer_id);return `<div class="list-row"><div class="list-main"><b>${q.quote_no}</b><small>${c?.name||'Cari'} · ${date(q.date||q.created_at)}</small></div><div><b>${money(q.total)}</b><br><span class="badge ${q.status==='Onaylandı'?'ok':q.status==='Reddedildi'?'danger':'warn'}">${q.status}</span></div></div>`}).join(''):'<p class="muted">Henüz teklif yok.</p>';const low=state.products.filter(p=>Number(p.stock)<=5);$('#low-stock-list').innerHTML=low.length?low.map(p=>`<div class="list-row"><div class="list-main"><b>${p.name}</b><small>${p.code}</small></div><span class="badge danger">${p.stock} ${p.unit}</span></div>`).join(''):'<p class="muted">Kritik stok yok. Harika.</p>'}
function renderProducts(filter=''){$('#products-body').innerHTML=state.products.filter(p=>(`${p.code} ${p.name} ${p.category}`).toLocaleLowerCase('tr').includes(filter.toLocaleLowerCase('tr'))).map(p=>`<tr><td><b>${p.code}</b></td><td>${p.name}</td><td>${p.category||'-'}</td><td><span class="badge ${Number(p.stock)<=5?'danger':Number(p.stock)<=15?'warn':'ok'}">${p.stock}</span></td><td>${p.unit}</td><td>${money(p.purchase)}</td><td>${money(p.sale)}</td><td><button class="text-btn" data-edit-product="${p.id}">Düzenle</button></td></tr>`).join('')||'<tr><td colspan="8" class="muted">Kayıt bulunamadı.</td></tr>'}
function renderCustomers(filter=''){$('#customers-body').innerHTML=state.customers.filter(c=>(`${c.name} ${c.contact} ${c.phone} ${c.tax_no}`).toLocaleLowerCase('tr').includes(filter.toLocaleLowerCase('tr'))).map(c=>`<tr><td><b>${c.name}</b></td><td>${c.contact||'-'}</td><td>${c.phone||'-'}</td><td>${c.tax_no||'-'}</td><td class="${Number(c.balance)>0?'':'muted'}">${money(c.balance)}</td><td><span class="badge info">${c.type||'Müşteri'}</span></td><td><button class="text-btn" data-edit-customer="${c.id}">Düzenle</button></td></tr>`).join('')||'<tr><td colspan="7" class="muted">Kayıt bulunamadı.</td></tr>'}
function renderQuotes(filter=''){$('#quotes-body').innerHTML=state.quotes.filter(q=>{const c=state.customers.find(x=>x.id===q.customer_id);return `${q.quote_no} ${c?.name||''}`.toLocaleLowerCase('tr').includes(filter.toLocaleLowerCase('tr'))}).map(q=>{const c=state.customers.find(x=>x.id===q.customer_id);return `<tr><td><b>${q.quote_no}</b></td><td>${c?.name||'-'}</td><td>${date(q.date||q.created_at)}</td><td>${q.items_count||0}</td><td><b>${money(q.total)}</b></td><td><span class="badge ${q.status==='Onaylandı'?'ok':q.status==='Reddedildi'?'danger':'warn'}">${q.status}</span></td><td><button class="text-btn" data-edit-quote="${q.id}">Görüntüle</button></td></tr>`}).join('')||'<tr><td colspan="7" class="muted">Teklif bulunamadı.</td></tr>'}
function renderMovements(){$('#movements-body').innerHTML=state.movements.map(m=>{const p=state.products.find(x=>x.id===m.product_id);return `<tr><td>${date(m.created_at)}</td><td>${p?.name||m.product_name||'-'}</td><td><span class="badge ${m.type==='Giriş'?'ok':'danger'}">${m.type}</span></td><td>${m.qty}</td><td>${m.note||'-'}</td></tr>`}).join('')||'<tr><td colspan="5" class="muted">Hareket yok.</td></tr>'}
function fieldsFor(type,item={}){if(type==='product')return [{n:'code',l:'Stok kodu',v:item.code||'',r:1},{n:'name',l:'Ürün adı',v:item.name||'',r:1},{n:'category',l:'Kategori',v:item.category||''},{n:'stock',l:'Mevcut stok',v:item.stock??0,t:'number'},{n:'unit',l:'Birim',v:item.unit||'adet'},{n:'purchase',l:'Alış fiyatı',v:item.purchase??0,t:'number'},{n:'sale',l:'Satış fiyatı',v:item.sale??0,t:'number'}];if(type==='customer')return [{n:'name',l:'Unvan / Ad Soyad',v:item.name||'',r:1},{n:'contact',l:'Yetkili',v:item.contact||''},{n:'phone',l:'Telefon',v:item.phone||''},{n:'tax_no',l:'Vergi / T.C. No',v:item.tax_no||''},{n:'balance',l:'Bakiye',v:item.balance??0,t:'number'},{n:'type',l:'Tip',v:item.type||'Müşteri'}];if(type==='movement')return [{n:'product_id',l:'Ürün',v:item.product_id||'',type:'select',options:state.products.map(p=>[p.id,`${p.code} — ${p.name}`])},{n:'type',l:'Hareket',v:item.type||'Giriş',type:'select',options:[['Giriş','Giriş'],['Çıkış','Çıkış']]},{n:'qty',l:'Miktar',v:item.qty??1,t:'number'},{n:'note',l:'Açıklama',v:item.note||''}];if(type==='quote')return [{n:'customer_id',l:'Müşteri',v:item.customer_id||'',type:'select',options:state.customers.map(c=>[c.id,c.name])},{n:'quote_no',l:'Teklif no',v:item.quote_no||`TKL-${new Date().getFullYear()}-${String(state.quotes.length+1).padStart(3,'0')}`},{n:'date',l:'Tarih',v:item.date||new Date().toISOString().slice(0,10),t:'date'},{n:'items_count',l:'Kalem sayısı',v:item.items_count??1,t:'number'},{n:'total',l:'Toplam',v:item.total??0,t:'number'},{n:'status',l:'Durum',v:item.status||'Bekliyor'}];return []}
function openModal(type,item={},id=null){const modal=$('#modal');$('#modal-title').textContent=id?'Kaydı düzenle':({product:'Yeni stok kartı',customer:'Yeni cari kartı',movement:'Yeni stok hareketi',quote:'Yeni teklif'}[type]);const form=$('#modal-form');form.dataset.type=type;form.dataset.id=id||'';form.innerHTML=fieldsFor(type,item).map(f=>{if(f.type==='select')return `<label>${f.l}<select name="${f.n}">${f.options.map(o=>`<option value="${o[0]}" ${String(o[0])===String(f.v)?'selected':''}>${o[1]}</option>`).join('')}</select></label>`;return `<label>${f.l}<input name="${f.n}" type="${f.t||'text'}" value="${String(f.v).replaceAll('"','&quot;')}" ${f.r?'required':''}></label>`}).join('');modal.showModal()}
async function saveModal(e){e.preventDefault();const form=e.target,type=form.dataset.type,id=form.dataset.id;const data=Object.fromEntries(new FormData(form).entries());for(const k of Object.keys(data))if(['stock','purchase','sale','balance','qty','items_count','total'].includes(k))data[k]=Number(data[k]||0);if(type==='movement')data.created_at=new Date().toISOString();if(type==='quote')data.created_at=new Date().toISOString();let list=type==='product'?'products':type==='customer'?'customers':type==='movement'?'stock_movements':'quotes';try{if(sb&&!state.demo){const r=id?await sb.from(list).update(data).eq('id',id):await sb.from(list).insert(data);if(r.error)throw r.error;await loadData()}else{if(id){const arr=state[list==='stock_movements'?'movements':list];const i=arr.findIndex(x=>x.id===id);if(i>-1)arr[i]={...arr[i],...data}}else{const arr=state[list==='stock_movements'?'movements':list];arr.unshift({id:crypto.randomUUID(),...data})}if(type==='movement'){const p=state.products.find(x=>x.id===data.product_id);if(p)p.stock+=data.type==='Giriş'?data.qty:-data.qty} }$('#modal').close();renderAll();toast('Kayıt kaydedildi')}catch(err){toast(err.message||'Kayıt sırasında hata oluştu','bad')}}
function wire(){ $('#login-form').addEventListener('submit',login);$('#demo-btn').addEventListener('click',loadDemo);$('#logout-btn').addEventListener('click',logout);$('#settings-logout').addEventListener('click',logout);$('#modal-close').addEventListener('click',()=>$('#modal').close());$('#modal-cancel').addEventListener('click',()=>$('#modal').close());$('#modal-form').addEventListener('submit',saveModal);$('#menu-btn').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));$$('[data-page]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.page)));$$('[data-page-jump]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.pageJump)));$('#add-product').addEventListener('click',()=>openModal('product'));$('#add-customer').addEventListener('click',()=>openModal('customer'));$('#add-quote').addEventListener('click',()=>openModal('quote'));$('#add-movement').addEventListener('click',()=>openModal('movement'));$('#global-add').addEventListener('click',()=>openModal(state.page==='products'?'product':state.page==='customers'?'customer':state.page==='movements'?'movement':'quote'));$('#product-search').addEventListener('input',e=>renderProducts(e.target.value));$('#customer-search').addEventListener('input',e=>renderCustomers(e.target.value));$('#quote-search').addEventListener('input',e=>renderQuotes(e.target.value));document.addEventListener('click',e=>{const p=e.target.closest('[data-edit-product]');if(p){const x=state.products.find(i=>i.id===p.dataset.editProduct);openModal('product',x,x.id)}const c=e.target.closest('[data-edit-customer]');if(c){const x=state.customers.find(i=>i.id===c.dataset.editCustomer);openModal('customer',x,x.id)}const q=e.target.closest('[data-edit-quote]');if(q){const x=state.quotes.find(i=>i.id===q.dataset.editQuote);openModal('quote',x,x.id)}})}
async function boot(){wire();if(sb){const {data}=await sb.auth.getSession();if(data.session){state.user=data.session.user;try{await loadData();enterApp()}catch(e){toast('Veriler yüklenemedi: '+e.message,'bad')}}else{$('#auth-note').textContent='Supabase hazır. E-posta ve şifren ile giriş yapabilir veya demo modunu kullanabilirsin.';setConnection('Giriş bekleniyor')}}else{$('#auth-note').textContent='Canlı bağlantı anahtarı eklenene kadar Demo modu ile tüm arayüzü deneyebilirsin.';setConnection('Demo hazır')}}
boot();
