const CONFIG={url:'https://miznxoykfoanazcitmit.supabase.co',key:'sb_publishable_F3fq67Aqp42zaXrhhKFEoQ_1zy1_6xA'};
const sb=window.supabase.createClient(CONFIG.url,CONFIG.key);
const state={demo:false,user:null,page:'dashboard',products:[],customers:[],quotes:[],movements:[]};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:2}).format(Number(n)||0);
const date=n=>n?new Intl.DateTimeFormat('tr-TR',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(n)):'-';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function toast(text,type='ok'){const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=text;$('#toast-root').append(el);setTimeout(()=>el.remove(),3000)}
const demo={products:[{id:'p1',code:'KAB-001',name:'3x2,5 NYM Kablo',category:'Kablo',stock:148,min_stock:10,unit:'m',purchase:42.5,sale:58},{id:'p2',code:'SİG-010',name:'Otomat Sigorta C16',category:'Pano',stock:7,min_stock:10,unit:'adet',purchase:95,sale:135},{id:'p3',code:'KON-025',name:'Kontaktör 25A',category:'Pano',stock:23,min_stock:5,unit:'adet',purchase:420,sale:575},{id:'p4',code:'KLM-050',name:'Klemens 4mm',category:'Pano',stock:4,min_stock:10,unit:'adet',purchase:18,sale:29}],customers:[{id:'c1',name:'Örnek Otomasyon Ltd. Şti.',contact:'Ahmet Yılmaz',phone:'0532 000 00 00',tax_no:'1234567890',balance:18450,type:'Müşteri'},{id:'c2',name:'HIS Elektrik',contact:'Mehmet Kaya',phone:'0541 000 00 00',tax_no:'9876543210',balance:-6250,type:'Tedarikçi'}],quotes:[{id:'q1',quote_no:'TKL-2026-001',customer_id:'c1',date:'2026-08-15',items_count:6,total:38750,status:'Bekliyor'},{id:'q2',quote_no:'TKL-2026-002',customer_id:'c2',date:'2026-08-14',items_count:3,total:12600,status:'Onaylandı'}],movements:[{id:'m1',product_id:'p1',product_name:'3x2,5 NYM Kablo',type:'Giriş',qty:100,note:'Depo girişi',created_at:'2026-08-15'},{id:'m2',product_id:'p2',product_name:'Otomat Sigorta C16',type:'Çıkış',qty:8,note:'Pano üretimi',created_at:'2026-08-14'}]};
function loadDemo(){state.demo=true;Object.keys(demo).forEach(k=>state[k]=structuredClone(demo[k]));state.user={email:'demo@stokteklif.local'};enterApp()}
function enterApp(){ $('#auth-view').classList.add('hidden');$('#app-view').classList.remove('hidden');$('#user-email').textContent=state.user?.email||'Demo kullanıcı';setConnection(state.demo?'Demo modu':'Supabase');renderAll() }
function setConnection(label){$('#connection-label').textContent=label;$('#settings-connection').textContent=label;$('#connection-dot').className='dot '+(label==='Supabase'?'ok':'')}
async function login(e){e.preventDefault();const email=$('#login-email').value.trim(),password=$('#login-password').value;const {data,error}=await sb.auth.signInWithPassword({email,password});if(error){toast(error.message,'bad');return}state.user=data.user;try{await loadData();enterApp();toast('Giriş başarılı')}catch(err){console.error(err);await sb.auth.signOut();toast(`Veri bağlantısı hatası: ${err.message}`,'bad')}}
async function logout(){if(!state.demo)await sb.auth.signOut();state.user=null;state.demo=false;$('#app-view').classList.add('hidden');$('#auth-view').classList.remove('hidden')}
function mapProduct(p){return {...p,id:p.id,code:p.product_code,name:p.product_name,stock:Number(p.stock_quantity||0),min_stock:Number(p.critical_stock_level||0),unit:'adet',purchase:Number(p.purchase_price||0),sale:Number(p.sale_price||0),vat:Number(p.vat_rate||20),active:p.is_active}}
function mapCustomer(c){return {...c,id:c.id,name:c.company_name,contact:c.contact_person,phone:c.phone,tax_no:c.tax_number,balance:Number(c.balance||0),type:c.type||'Müşteri',active:c.is_active}}
const quoteStatus={DRAFT:'Taslak',SENT:'Bekliyor',APPROVED:'Onaylandı',REJECTED:'Reddedildi',EXPIRED:'Süresi Doldu',CANCELLED:'İptal'};
const quoteStatusRev={Taslak:'DRAFT',Bekliyor:'SENT','Onaylandı':'APPROVED',Reddedildi:'REJECTED','Süresi Doldu':'EXPIRED',İptal:'CANCELLED'};
function mapQuote(q,count=0){return {...q,id:q.id,quote_no:q.quote_number,customer_id:q.customer_id,date:q.quote_date,valid_until:q.valid_until,items_count:count,subtotal:Number(q.subtotal||0),discount:Number(q.discount_amount||0),vat_total:Number(q.vat_amount||0),total:Number(q.grand_total||0),status:quoteStatus[q.status]||q.status}}
function mapMovement(m){const type=m.transaction_type==='IN'?'Giriş':m.transaction_type==='OUT'?'Çıkış':'Fire';return {...m,id:m.id,product_id:m.product_id,type,qty:Number(m.quantity||0),unit_cost:Number(m.unit_price||0),note:m.description||'',created_at:m.transaction_date||m.created_at}}
async function loadData(){const [p,c,q,m,qi]=await Promise.all([sb.from('products').select('*').eq('is_active',true).order('product_name'),sb.from('customers').select('*').eq('is_active',true).order('company_name'),sb.from('quotes').select('*').eq('is_active',true).order('created_at',{ascending:false}),sb.from('stock_transactions').select('*').order('transaction_date',{ascending:false}),sb.from('quote_items').select('quote_id')]);for(const r of [p,c,q,m,qi])if(r.error)throw r.error;const counts={};(qi.data||[]).forEach(x=>counts[x.quote_id]=(counts[x.quote_id]||0)+1);state.products=(p.data||[]).map(mapProduct);state.customers=(c.data||[]).map(mapCustomer);state.quotes=(q.data||[]).map(x=>mapQuote(x,counts[x.id]||0));state.movements=(m.data||[]).map(mapMovement)}
function navigate(page){state.page=page;$$('.page').forEach(x=>x.classList.remove('active-page'));$(`#page-${page}`).classList.add('active-page');$$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$$('.bottom-nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===page));const titles={dashboard:['GENEL BAKIŞ','Dashboard'],products:['ENVANTER','Stoklar'],customers:['CARİ YÖNETİMİ','Cariler'],quotes:['SATIŞ','Teklifler'],movements:['HAREKET','Stok Hareketleri'],settings:['SİSTEM','Ayarlar']};$('#page-kicker').textContent=titles[page][0];$('#page-title').textContent=titles[page][1];$('#sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
function renderAll(){renderStats();renderProducts();renderCustomers();renderQuotes();renderMovements();renderDashboard()}
function renderStats(){const low=state.products.filter(p=>Number(p.stock)<=Number(p.min_stock||5)).length;const balance=state.customers.reduce((a,c)=>a+Number(c.balance||0),0);$('#stat-products').textContent=state.products.length;$('#stat-low').textContent=low;$('#stat-quotes').textContent=state.quotes.length;$('#stat-balance').textContent=money(balance)}
function renderDashboard(){const qs=state.quotes.slice(0,5);$('#recent-quotes').innerHTML=qs.length?qs.map(q=>{const c=state.customers.find(x=>x.id===q.customer_id);return `<div class="list-row"><div class="list-main"><b>${esc(q.quote_no)}</b><small>${esc(c?.name||'Cari')} · ${date(q.date)}</small></div><div><b>${money(q.total)}</b><br><span class="badge ${q.status==='Onaylandı'?'ok':q.status==='Reddedildi'?'danger':'warn'}">${esc(q.status)}</span></div></div>`}).join(''):'<p class="muted">Henüz teklif yok.</p>';const low=state.products.filter(p=>Number(p.stock)<=Number(p.min_stock||5));$('#low-stock-list').innerHTML=low.length?low.map(p=>`<div class="list-row"><div class="list-main"><b>${esc(p.name)}</b><small>${esc(p.code)}</small></div><span class="badge danger">${p.stock} ${esc(p.unit)}</span></div>`).join(''):'<p class="muted">Kritik stok yok. Harika.</p>'}
function renderProducts(filter=''){const f=filter.toLocaleLowerCase('tr');$('#products-body').innerHTML=state.products.filter(p=>`${p.code} ${p.name} ${p.category||''}`.toLocaleLowerCase('tr').includes(f)).map(p=>`<tr><td><b>${esc(p.code)}</b></td><td>${esc(p.name)}</td><td>${esc(p.category||'-')}</td><td><span class="badge ${Number(p.stock)<=Number(p.min_stock||5)?'danger':Number(p.stock)<=15?'warn':'ok'}">${p.stock}</span></td><td>${esc(p.unit)}</td><td>${money(p.purchase)}</td><td>${money(p.sale)}</td><td><button class="text-btn" data-edit-product="${p.id}">Düzenle</button></td></tr>`).join('')||'<tr><td colspan="8" class="muted">Kayıt bulunamadı.</td></tr>'}
function renderCustomers(filter=''){const f=filter.toLocaleLowerCase('tr');$('#customers-body').innerHTML=state.customers.filter(c=>`${c.name} ${c.contact||''} ${c.phone||''} ${c.tax_no||''}`.toLocaleLowerCase('tr').includes(f)).map(c=>`<tr><td><b>${esc(c.name)}</b></td><td>${esc(c.contact||'-')}</td><td>${esc(c.phone||'-')}</td><td>${esc(c.tax_no||'-')}</td><td>${money(c.balance)}</td><td><span class="badge info">${esc(c.type)}</span></td><td><button class="text-btn" data-edit-customer="${c.id}">Düzenle</button></td></tr>`).join('')||'<tr><td colspan="7" class="muted">Kayıt bulunamadı.</td></tr>'}
function renderQuotes(filter=''){const f=filter.toLocaleLowerCase('tr');$('#quotes-body').innerHTML=state.quotes.filter(q=>{const c=state.customers.find(x=>x.id===q.customer_id);return `${q.quote_no} ${c?.name||''}`.toLocaleLowerCase('tr').includes(f)}).map(q=>{const c=state.customers.find(x=>x.id===q.customer_id);return `<tr><td><b>${esc(q.quote_no)}</b></td><td>${esc(c?.name||'-')}</td><td>${date(q.date)}</td><td>${q.items_count}</td><td><b>${money(q.total)}</b></td><td><span class="badge ${q.status==='Onaylandı'?'ok':q.status==='Reddedildi'?'danger':'warn'}">${esc(q.status)}</span></td><td><button class="text-btn" data-edit-quote="${q.id}">Görüntüle</button></td></tr>`}).join('')||'<tr><td colspan="7" class="muted">Teklif bulunamadı.</td></tr>'}
function renderMovements(){$('#movements-body').innerHTML=state.movements.map(m=>{const p=state.products.find(x=>x.id===m.product_id);return `<tr><td>${date(m.created_at)}</td><td>${esc(p?.name||m.product_name||'-')}</td><td><span class="badge ${m.type==='Giriş'?'ok':'danger'}">${esc(m.type)}</span></td><td>${m.qty}</td><td>${esc(m.note||'-')}</td></tr>`}).join('')||'<tr><td colspan="5" class="muted">Hareket yok.</td></tr>'}
function fieldsFor(type,item={}){if(type==='product')return [{n:'code',l:'Stok kodu',v:item.code||'',r:1},{n:'name',l:'Ürün adı',v:item.name||'',r:1},{n:'category',l:'Kategori',v:item.category||''},{n:'stock',l:'Mevcut stok',v:item.stock??0,t:'number'},{n:'min_stock',l:'Kritik stok seviyesi',v:item.min_stock??5,t:'number'},{n:'unit',l:'Birim',v:item.unit||'adet'},{n:'purchase',l:'Alış fiyatı',v:item.purchase??0,t:'number'},{n:'sale',l:'Satış fiyatı',v:item.sale??0,t:'number'},{n:'vat',l:'KDV %',v:item.vat??20,t:'number'}];if(type==='customer')return [{n:'name',l:'Unvan / Ad Soyad',v:item.name||'',r:1},{n:'contact',l:'Yetkili',v:item.contact||''},{n:'phone',l:'Telefon',v:item.phone||''},{n:'email',l:'E-posta',v:item.email||'',t:'email'},{n:'tax_no',l:'Vergi / T.C. No',v:item.tax_no||''},{n:'tax_office',l:'Vergi Dairesi',v:item.tax_office||''},{n:'address',l:'Adres',v:item.address||''},{n:'balance',l:'Bakiye',v:item.balance??0,t:'number'},{n:'type',l:'Tip',v:item.type||'Müşteri'}];if(type==='movement')return [{n:'product_id',l:'Ürün',v:item.product_id||'',type:'select',options:state.products.map(p=>[p.id,`${p.code} — ${p.name}`])},{n:'type',l:'Hareket',v:item.type||'Giriş',type:'select',options:[['Giriş','Giriş'],['Çıkış','Çıkış'],['Fire','Fire']]},{n:'qty',l:'Miktar',v:item.qty??1,t:'number'},{n:'unit_cost',l:'Birim fiyat',v:item.unit_cost??0,t:'number'},{n:'note',l:'Açıklama',v:item.note||''}];if(type==='quote')return [{n:'customer_id',l:'Müşteri',v:item.customer_id||'',type:'select',options:state.customers.map(c=>[c.id,c.name])},{n:'quote_no',l:'Teklif no',v:item.quote_no||`TKL-${new Date().getFullYear()}-${String(state.quotes.length+1).padStart(3,'0')}`},{n:'date',l:'Tarih',v:item.date||new Date().toISOString().slice(0,10),t:'date'},{n:'valid_until',l:'Geçerlilik',v:item.valid_until||'',t:'date'},{n:'subtotal',l:'Ara toplam',v:item.subtotal??0,t:'number'},{n:'discount',l:'İskonto',v:item.discount??0,t:'number'},{n:'vat_total',l:'KDV',v:item.vat_total??0,t:'number'},{n:'total',l:'Genel toplam',v:item.total??0,t:'number'},{n:'status',l:'Durum',v:item.status||'Bekliyor',type:'select',options:Object.keys(quoteStatusRev).map(x=>[x,x])}];return []}
function openModal(type,item={},id=null){$('#modal-title').textContent=id?'Kaydı düzenle':({product:'Yeni stok kartı',customer:'Yeni cari kartı',movement:'Yeni stok hareketi',quote:'Yeni teklif'}[type]);const form=$('#modal-form');form.dataset.type=type;form.dataset.id=id||'';form.innerHTML=fieldsFor(type,item).map(f=>f.type==='select'?`<label>${f.l}<select name="${f.n}">${f.options.map(o=>`<option value="${esc(o[0])}" ${String(o[0])===String(f.v)?'selected':''}>${esc(o[1])}</option>`).join('')}</select></label>`:`<label>${f.l}<input name="${f.n}" type="${f.t||'text'}" value="${esc(f.v)}" ${f.r?'required':''}></label>`).join('');$('#modal').showModal()}
function payload(type,raw,id){if(type==='product')return {product_code:raw.code,product_name:raw.name,category:raw.category||null,stock_quantity:Number(raw.stock||0),critical_stock_level:Number(raw.min_stock||0),purchase_price:Number(raw.purchase||0),sale_price:Number(raw.sale||0),vat_rate:Number(raw.vat||20),is_active:true};if(type==='customer')return {company_name:raw.name,contact_person:raw.contact||null,phone:raw.phone||null,email:raw.email||null,tax_number:raw.tax_no||null,tax_office:raw.tax_office||null,address:raw.address||null,is_active:true};if(type==='quote')return {quote_number:raw.quote_no,customer_id:raw.customer_id||null,quote_date:raw.date,valid_until:raw.valid_until||null,subtotal:Number(raw.subtotal||0),discount_amount:Number(raw.discount||0),vat_amount:Number(raw.vat_total||0),grand_total:Number(raw.total||0),status:quoteStatusRev[raw.status]||'SENT',is_active:true};return {product_id:raw.product_id,transaction_type:raw.type==='Giriş'?'IN':raw.type==='Çıkış'?'OUT':'WASTE',quantity:Number(raw.qty||0),unit_price:Number(raw.unit_cost||0),description:raw.note||null,transaction_date:new Date().toISOString()}}
async function saveModal(e){e.preventDefault();const form=e.target,type=form.dataset.type,id=form.dataset.id;const raw=Object.fromEntries(new FormData(form).entries());try{if(state.demo){const map={product:'products',customer:'customers',quote:'quotes',movement:'movements'},arr=state[map[type]];const d=type==='product'?{id:id||crypto.randomUUID(),...raw,code:raw.code,name:raw.name,stock:Number(raw.stock),min_stock:Number(raw.min_stock),purchase:Number(raw.purchase),sale:Number(raw.sale)}:type==='customer'?{id:id||crypto.randomUUID(),...raw,name:raw.name,balance:Number(raw.balance||0)}:type==='quote'?{id:id||crypto.randomUUID(),...raw,quote_no:raw.quote_no,total:Number(raw.total),items_count:1}: {id:id||crypto.randomUUID(),product_id:raw.product_id,type:raw.type,qty:Number(raw.qty),note:raw.note,created_at:new Date().toISOString()};if(id){const i=arr.findIndex(x=>x.id===id);if(i>-1)arr[i]={...arr[i],...d}}else arr.unshift(d)}else{const table=type==='product'?'products':type==='customer'?'customers':type==='quote'?'quotes':'stock_transactions';let d=payload(type,raw,id);if(!id)d.created_by=state.user.id;if(id){const q=await sb.from(table).update(d).eq('id',id);if(q.error)throw q.error}else{const q=await sb.from(table).insert(d);if(q.error)throw q.error}await loadData()}$('#modal').close();renderAll();toast('Kayıt kaydedildi')}catch(err){console.error(err);toast(err.message||'Kayıt sırasında hata oluştu','bad')}}
function wire(){ $('#login-form').addEventListener('submit',login);$('#demo-btn').addEventListener('click',loadDemo);$('#logout-btn').addEventListener('click',logout);$('#settings-logout').addEventListener('click',logout);$('#modal-close').addEventListener('click',()=>$('#modal').close());$('#modal-cancel').addEventListener('click',()=>$('#modal').close());$('#modal-form').addEventListener('submit',saveModal);$('#menu-btn').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));$$('[data-page]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.page)));$$('[data-page-jump]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.pageJump)));$('#add-product').addEventListener('click',()=>openModal('product'));$('#add-customer').addEventListener('click',()=>openModal('customer'));$('#add-quote').addEventListener('click',()=>openModal('quote'));$('#add-movement').addEventListener('click',()=>openModal('movement'));$('#global-add').addEventListener('click',()=>openModal(state.page==='products'?'product':state.page==='customers'?'customer':state.page==='movements'?'movement':'quote'));$('#product-search').addEventListener('input',e=>renderProducts(e.target.value));$('#customer-search').addEventListener('input',e=>renderCustomers(e.target.value));$('#quote-search').addEventListener('input',e=>renderQuotes(e.target.value));document.addEventListener('click',e=>{const p=e.target.closest('[data-edit-product]');if(p){const x=state.products.find(v=>v.id===p.dataset.editProduct);openModal('product',x,x.id)}const c=e.target.closest('[data-edit-customer]');if(c){const x=state.customers.find(v=>v.id===c.dataset.editCustomer);openModal('customer',x,x.id)}const q=e.target.closest('[data-edit-quote]');if(q){const x=state.quotes.find(v=>v.id===q.dataset.editQuote);openModal('quote',x,x.id)}})}
async function boot(){wire();const {data}=await sb.auth.getSession();if(data.session){state.user=data.session.user;try{await loadData();enterApp()}catch(err){console.error(err);await sb.auth.signOut();toast(`Oturum verisi yüklenemedi: ${err.message}`,'bad')}}}
boot();